### ISSUE TITLE
Add ability to set auditd to `rotate` logs

### ISSUE THREAD

**Issue by gw0** [francsw/ubuntu2204_cis#1]
**Is your feature request related to a problem? Please describe.**
The CIS Ubuntu 22.04 benchmark recommends configuring auditd to `keep` all logs, but this will eventually lead to an out-of-disk situation. Therefore it is more sane to set auditd to `rotate` logs, but `rotate` also requires `num_logs` is configured. Unfortunately, this CIS role does not support configuring `num_logs`.

**Describe the solution you'd like**
I would like to have the ability to set auditd to `rotate` logs, which would require a configuration like:
```
ubuntu2204cis_auditd:
  max_log_file_action: rotate
  num_logs: 99
```
This could easily be implemented by adding:
```
- name: Patch auditd logs num_logs setting.
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: ^num_logs
      line: num_logs = {{ ubuntu2204cis_auditd.num_logs }}
      state: present
      create: yes
  notify:
      - restart auditd
```

**Describe alternatives you've considered**
An alternative is to have a "patch" role to run after this CIS role.
